<?php
namespace Aws\ObservabilityAdmin;

use Aws\AwsClient;

/**
 * This client is used to interact with the **CloudWatch Observability Admin Service** service.
 * @method \Aws\Result createTelemetryRule(array $args = [])
 * @method \GuzzleHttp\Promise\Promise createTelemetryRuleAsync(array $args = [])
 * @method \Aws\Result createTelemetryRuleForOrganization(array $args = [])
 * @method \GuzzleHttp\Promise\Promise createTelemetryRuleForOrganizationAsync(array $args = [])
 * @method \Aws\Result deleteTelemetryRule(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deleteTelemetryRuleAsync(array $args = [])
 * @method \Aws\Result deleteTelemetryRuleForOrganization(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deleteTelemetryRuleForOrganizationAsync(array $args = [])
 * @method \Aws\Result getTelemetryEvaluationStatus(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getTelemetryEvaluationStatusAsync(array $args = [])
 * @method \Aws\Result getTelemetryEvaluationStatusForOrganization(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getTelemetryEvaluationStatusForOrganizationAsync(array $args = [])
 * @method \Aws\Result getTelemetryRule(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getTelemetryRuleAsync(array $args = [])
 * @method \Aws\Result getTelemetryRuleForOrganization(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getTelemetryRuleForOrganizationAsync(array $args = [])
 * @method \Aws\Result listResourceTelemetry(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listResourceTelemetryAsync(array $args = [])
 * @method \Aws\Result listResourceTelemetryForOrganization(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listResourceTelemetryForOrganizationAsync(array $args = [])
 * @method \Aws\Result listTagsForResource(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listTagsForResourceAsync(array $args = [])
 * @method \Aws\Result listTelemetryRules(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listTelemetryRulesAsync(array $args = [])
 * @method \Aws\Result listTelemetryRulesForOrganization(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listTelemetryRulesForOrganizationAsync(array $args = [])
 * @method \Aws\Result startTelemetryEvaluation(array $args = [])
 * @method \GuzzleHttp\Promise\Promise startTelemetryEvaluationAsync(array $args = [])
 * @method \Aws\Result startTelemetryEvaluationForOrganization(array $args = [])
 * @method \GuzzleHttp\Promise\Promise startTelemetryEvaluationForOrganizationAsync(array $args = [])
 * @method \Aws\Result stopTelemetryEvaluation(array $args = [])
 * @method \GuzzleHttp\Promise\Promise stopTelemetryEvaluationAsync(array $args = [])
 * @method \Aws\Result stopTelemetryEvaluationForOrganization(array $args = [])
 * @method \GuzzleHttp\Promise\Promise stopTelemetryEvaluationForOrganizationAsync(array $args = [])
 * @method \Aws\Result tagResource(array $args = [])
 * @method \GuzzleHttp\Promise\Promise tagResourceAsync(array $args = [])
 * @method \Aws\Result untagResource(array $args = [])
 * @method \GuzzleHttp\Promise\Promise untagResourceAsync(array $args = [])
 * @method \Aws\Result updateTelemetryRule(array $args = [])
 * @method \GuzzleHttp\Promise\Promise updateTelemetryRuleAsync(array $args = [])
 * @method \Aws\Result updateTelemetryRuleForOrganization(array $args = [])
 * @method \GuzzleHttp\Promise\Promise updateTelemetryRuleForOrganizationAsync(array $args = [])
 */
class ObservabilityAdminClient extends AwsClient {}
