<?php
namespace Aws\ClientSideMonitoring\Exception;
use Aws\HasMonitoringEventsTrait;


/**
 * Represents an error generated by the SDK for client-side monitoring.
 */
class SdkException extends \Exception
{
    use HasMonitoringEventsTrait;
}
