<?php
namespace Aws\HealthLake;

use Aws\AwsClient;

/**
 * This client is used to interact with the **Amazon HealthLake** service.
 * @method \Aws\Result createDataTransformationProfile(array $args = [])
 * @method \GuzzleHttp\Promise\Promise createDataTransformationProfileAsync(array $args = [])
 * @method \Aws\Result createFHIRDatastore(array $args = [])
 * @method \GuzzleHttp\Promise\Promise createFHIRDatastoreAsync(array $args = [])
 * @method \Aws\Result deleteDataTransformationProfile(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deleteDataTransformationProfileAsync(array $args = [])
 * @method \Aws\Result deleteFHIRDatastore(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deleteFHIRDatastoreAsync(array $args = [])
 * @method \Aws\Result describeDataTransformationJob(array $args = [])
 * @method \GuzzleHttp\Promise\Promise describeDataTransformationJobAsync(array $args = [])
 * @method \Aws\Result describeFHIRDatastore(array $args = [])
 * @method \GuzzleHttp\Promise\Promise describeFHIRDatastoreAsync(array $args = [])
 * @method \Aws\Result describeFHIRExportJob(array $args = [])
 * @method \GuzzleHttp\Promise\Promise describeFHIRExportJobAsync(array $args = [])
 * @method \Aws\Result describeFHIRImportJob(array $args = [])
 * @method \GuzzleHttp\Promise\Promise describeFHIRImportJobAsync(array $args = [])
 * @method \Aws\Result getDataTransformationProfile(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getDataTransformationProfileAsync(array $args = [])
 * @method \Aws\Result listDataTransformationJobs(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listDataTransformationJobsAsync(array $args = [])
 * @method \Aws\Result listDataTransformationProfileVersions(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listDataTransformationProfileVersionsAsync(array $args = [])
 * @method \Aws\Result listDataTransformationProfiles(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listDataTransformationProfilesAsync(array $args = [])
 * @method \Aws\Result listFHIRDatastores(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listFHIRDatastoresAsync(array $args = [])
 * @method \Aws\Result listFHIRExportJobs(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listFHIRExportJobsAsync(array $args = [])
 * @method \Aws\Result listFHIRImportJobs(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listFHIRImportJobsAsync(array $args = [])
 * @method \Aws\Result listTagsForResource(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listTagsForResourceAsync(array $args = [])
 * @method \Aws\Result publishDataTransformationProfile(array $args = [])
 * @method \GuzzleHttp\Promise\Promise publishDataTransformationProfileAsync(array $args = [])
 * @method \Aws\Result startDataTransformationJob(array $args = [])
 * @method \GuzzleHttp\Promise\Promise startDataTransformationJobAsync(array $args = [])
 * @method \Aws\Result startFHIRExportJob(array $args = [])
 * @method \GuzzleHttp\Promise\Promise startFHIRExportJobAsync(array $args = [])
 * @method \Aws\Result startFHIRImportJob(array $args = [])
 * @method \GuzzleHttp\Promise\Promise startFHIRImportJobAsync(array $args = [])
 * @method \Aws\Result tagResource(array $args = [])
 * @method \GuzzleHttp\Promise\Promise tagResourceAsync(array $args = [])
 * @method \Aws\Result untagResource(array $args = [])
 * @method \GuzzleHttp\Promise\Promise untagResourceAsync(array $args = [])
 * @method \Aws\Result updateDataTransformationProfile(array $args = [])
 * @method \GuzzleHttp\Promise\Promise updateDataTransformationProfileAsync(array $args = [])
 * @method \Aws\Result updateFHIRDatastore(array $args = [])
 * @method \GuzzleHttp\Promise\Promise updateFHIRDatastoreAsync(array $args = [])
 * @method \Aws\Result updateProfileWithAgent(array $args = [])
 * @method \GuzzleHttp\Promise\Promise updateProfileWithAgentAsync(array $args = [])
 */
class HealthLakeClient extends AwsClient {}
