<?php
namespace Aws\Redshift;

use Aws\AwsClient;

/**
 * This client is used to interact with the **Amazon Redshift** service.
 *
 * @method \Aws\Result authorizeClusterSecurityGroupIngress(array $args = [])
 * @method \Aws\Result authorizeSnapshotAccess(array $args = [])
 * @method \Aws\Result copyClusterSnapshot(array $args = [])
 * @method \Aws\Result createCluster(array $args = [])
 * @method \Aws\Result createClusterParameterGroup(array $args = [])
 * @method \Aws\Result createClusterSecurityGroup(array $args = [])
 * @method \Aws\Result createClusterSnapshot(array $args = [])
 * @method \Aws\Result createClusterSubnetGroup(array $args = [])
 * @method \Aws\Result createEventSubscription(array $args = [])
 * @method \Aws\Result createHsmClientCertificate(array $args = [])
 * @method \Aws\Result createHsmConfiguration(array $args = [])
 * @method \Aws\Result createSnapshotCopyGrant(array $args = [])
 * @method \Aws\Result createTags(array $args = [])
 * @method \Aws\Result deleteCluster(array $args = [])
 * @method \Aws\Result deleteClusterParameterGroup(array $args = [])
 * @method \Aws\Result deleteClusterSecurityGroup(array $args = [])
 * @method \Aws\Result deleteClusterSnapshot(array $args = [])
 * @method \Aws\Result deleteClusterSubnetGroup(array $args = [])
 * @method \Aws\Result deleteEventSubscription(array $args = [])
 * @method \Aws\Result deleteHsmClientCertificate(array $args = [])
 * @method \Aws\Result deleteHsmConfiguration(array $args = [])
 * @method \Aws\Result deleteSnapshotCopyGrant(array $args = [])
 * @method \Aws\Result deleteTags(array $args = [])
 * @method \Aws\Result describeClusterParameterGroups(array $args = [])
 * @method \Aws\Result describeClusterParameters(array $args = [])
 * @method \Aws\Result describeClusterSecurityGroups(array $args = [])
 * @method \Aws\Result describeClusterSnapshots(array $args = [])
 * @method \Aws\Result describeClusterSubnetGroups(array $args = [])
 * @method \Aws\Result describeClusterVersions(array $args = [])
 * @method \Aws\Result describeClusters(array $args = [])
 * @method \Aws\Result describeDefaultClusterParameters(array $args = [])
 * @method \Aws\Result describeEventCategories(array $args = [])
 * @method \Aws\Result describeEventSubscriptions(array $args = [])
 * @method \Aws\Result describeEvents(array $args = [])
 * @method \Aws\Result describeHsmClientCertificates(array $args = [])
 * @method \Aws\Result describeHsmConfigurations(array $args = [])
 * @method \Aws\Result describeLoggingStatus(array $args = [])
 * @method \Aws\Result describeOrderableClusterOptions(array $args = [])
 * @method \Aws\Result describeReservedNodeOfferings(array $args = [])
 * @method \Aws\Result describeReservedNodes(array $args = [])
 * @method \Aws\Result describeResize(array $args = [])
 * @method \Aws\Result describeSnapshotCopyGrants(array $args = [])
 * @method \Aws\Result describeTags(array $args = [])
 * @method \Aws\Result disableLogging(array $args = [])
 * @method \Aws\Result disableSnapshotCopy(array $args = [])
 * @method \Aws\Result enableLogging(array $args = [])
 * @method \Aws\Result enableSnapshotCopy(array $args = [])
 * @method \Aws\Result modifyCluster(array $args = [])
 * @method \Aws\Result modifyClusterParameterGroup(array $args = [])
 * @method \Aws\Result modifyClusterSubnetGroup(array $args = [])
 * @method \Aws\Result modifyEventSubscription(array $args = [])
 * @method \Aws\Result modifySnapshotCopyRetentionPeriod(array $args = [])
 * @method \Aws\Result purchaseReservedNodeOffering(array $args = [])
 * @method \Aws\Result rebootCluster(array $args = [])
 * @method \Aws\Result resetClusterParameterGroup(array $args = [])
 * @method \Aws\Result restoreFromClusterSnapshot(array $args = [])
 * @method \Aws\Result revokeClusterSecurityGroupIngress(array $args = [])
 * @method \Aws\Result revokeSnapshotAccess(array $args = [])
 * @method \Aws\Result rotateEncryptionKey(array $args = [])
 */
class RedshiftClient extends AwsClient {}
