<?php
namespace Aws\Rds;

use Aws\AwsClient;

/**
 * This client is used to interact with the **Amazon Relational Database Service (Amazon RDS)**.
 *
 * @method \Aws\Result addSourceIdentifierToSubscription(array $args = [])
 * @method \Aws\Result addTagsToResource(array $args = [])
 * @method \Aws\Result applyPendingMaintenanceAction(array $args = [])
 * @method \Aws\Result authorizeDBSecurityGroupIngress(array $args = [])
 * @method \Aws\Result copyDBClusterSnapshot(array $args = [])
 * @method \Aws\Result copyDBParameterGroup(array $args = [])
 * @method \Aws\Result copyDBSnapshot(array $args = [])
 * @method \Aws\Result copyOptionGroup(array $args = [])
 * @method \Aws\Result createDBCluster(array $args = [])
 * @method \Aws\Result createDBClusterParameterGroup(array $args = [])
 * @method \Aws\Result createDBClusterSnapshot(array $args = [])
 * @method \Aws\Result createDBInstance(array $args = [])
 * @method \Aws\Result createDBInstanceReadReplica(array $args = [])
 * @method \Aws\Result createDBParameterGroup(array $args = [])
 * @method \Aws\Result createDBSecurityGroup(array $args = [])
 * @method \Aws\Result createDBSnapshot(array $args = [])
 * @method \Aws\Result createDBSubnetGroup(array $args = [])
 * @method \Aws\Result createEventSubscription(array $args = [])
 * @method \Aws\Result createOptionGroup(array $args = [])
 * @method \Aws\Result deleteDBCluster(array $args = [])
 * @method \Aws\Result deleteDBClusterParameterGroup(array $args = [])
 * @method \Aws\Result deleteDBClusterSnapshot(array $args = [])
 * @method \Aws\Result deleteDBInstance(array $args = [])
 * @method \Aws\Result deleteDBParameterGroup(array $args = [])
 * @method \Aws\Result deleteDBSecurityGroup(array $args = [])
 * @method \Aws\Result deleteDBSnapshot(array $args = [])
 * @method \Aws\Result deleteDBSubnetGroup(array $args = [])
 * @method \Aws\Result deleteEventSubscription(array $args = [])
 * @method \Aws\Result deleteOptionGroup(array $args = [])
 * @method \Aws\Result describeAccountAttributes(array $args = [])
 * @method \Aws\Result describeCertificates(array $args = [])
 * @method \Aws\Result describeDBClusterParameterGroups(array $args = [])
 * @method \Aws\Result describeDBClusterParameters(array $args = [])
 * @method \Aws\Result describeDBClusterSnapshots(array $args = [])
 * @method \Aws\Result describeDBClusters(array $args = [])
 * @method \Aws\Result describeDBEngineVersions(array $args = [])
 * @method \Aws\Result describeDBInstances(array $args = [])
 * @method \Aws\Result describeDBLogFiles(array $args = [])
 * @method \Aws\Result describeDBParameterGroups(array $args = [])
 * @method \Aws\Result describeDBParameters(array $args = [])
 * @method \Aws\Result describeDBSecurityGroups(array $args = [])
 * @method \Aws\Result describeDBSnapshots(array $args = [])
 * @method \Aws\Result describeDBSubnetGroups(array $args = [])
 * @method \Aws\Result describeEngineDefaultClusterParameters(array $args = [])
 * @method \Aws\Result describeEngineDefaultParameters(array $args = [])
 * @method \Aws\Result describeEventCategories(array $args = [])
 * @method \Aws\Result describeEventSubscriptions(array $args = [])
 * @method \Aws\Result describeEvents(array $args = [])
 * @method \Aws\Result describeOptionGroupOptions(array $args = [])
 * @method \Aws\Result describeOptionGroups(array $args = [])
 * @method \Aws\Result describeOrderableDBInstanceOptions(array $args = [])
 * @method \Aws\Result describePendingMaintenanceActions(array $args = [])
 * @method \Aws\Result describeReservedDBInstances(array $args = [])
 * @method \Aws\Result describeReservedDBInstancesOfferings(array $args = [])
 * @method \Aws\Result downloadDBLogFilePortion(array $args = [])
 * @method \Aws\Result failoverDBCluster(array $args = [])
 * @method \Aws\Result listTagsForResource(array $args = [])
 * @method \Aws\Result modifyDBCluster(array $args = [])
 * @method \Aws\Result modifyDBClusterParameterGroup(array $args = [])
 * @method \Aws\Result modifyDBInstance(array $args = [])
 * @method \Aws\Result modifyDBParameterGroup(array $args = [])
 * @method \Aws\Result modifyDBSubnetGroup(array $args = [])
 * @method \Aws\Result modifyEventSubscription(array $args = [])
 * @method \Aws\Result modifyOptionGroup(array $args = [])
 * @method \Aws\Result promoteReadReplica(array $args = [])
 * @method \Aws\Result purchaseReservedDBInstancesOffering(array $args = [])
 * @method \Aws\Result rebootDBInstance(array $args = [])
 * @method \Aws\Result removeSourceIdentifierFromSubscription(array $args = [])
 * @method \Aws\Result removeTagsFromResource(array $args = [])
 * @method \Aws\Result resetDBClusterParameterGroup(array $args = [])
 * @method \Aws\Result resetDBParameterGroup(array $args = [])
 * @method \Aws\Result restoreDBClusterFromSnapshot(array $args = [])
 * @method \Aws\Result restoreDBClusterToPointInTime(array $args = [])
 * @method \Aws\Result restoreDBInstanceFromDBSnapshot(array $args = [])
 * @method \Aws\Result restoreDBInstanceToPointInTime(array $args = [])
 * @method \Aws\Result revokeDBSecurityGroupIngress(array $args = [])
 */
class RdsClient extends AwsClient {}
