<?php
namespace Aws\Pipes;

use Aws\AwsClient;

/**
 * This client is used to interact with the **Amazon EventBridge Pipes** service.
 * @method \Aws\Result createPipe(array $args = [])
 * @phpstan-method \Aws\Result createPipe(array{
 *     Name?: string,
 *     Description?: string,
 *     DesiredState?: 'RUNNING'|'STOPPED',
 *     Source?: string,
 *     SourceParameters?: array{
 *         FilterCriteria?: array{Filters?: list<array>, ...},
 *         KinesisStreamParameters?: array{
 *             BatchSize?: int,
 *             DeadLetterConfig?: array,
 *             OnPartialBatchItemFailure?: 'AUTOMATIC_BISECT',
 *             MaximumBatchingWindowInSeconds?: int,
 *             MaximumRecordAgeInSeconds?: int,
 *             MaximumRetryAttempts?: int,
 *             ParallelizationFactor?: int,
 *             StartingPosition?: 'AT_TIMESTAMP'|'LATEST'|'TRIM_HORIZON',
 *             StartingPositionTimestamp?: int|string|\DateTimeInterface,
 *             ...,
 *         },
 *         DynamoDBStreamParameters?: array{
 *             BatchSize?: int,
 *             DeadLetterConfig?: array,
 *             OnPartialBatchItemFailure?: 'AUTOMATIC_BISECT',
 *             MaximumBatchingWindowInSeconds?: int,
 *             MaximumRecordAgeInSeconds?: int,
 *             MaximumRetryAttempts?: int,
 *             ParallelizationFactor?: int,
 *             StartingPosition?: 'LATEST'|'TRIM_HORIZON',
 *             ...,
 *         },
 *         SqsQueueParameters?: array{BatchSize?: int, MaximumBatchingWindowInSeconds?: int, ...},
 *         ActiveMQBrokerParameters?: array{Credentials?: array, QueueName?: string, BatchSize?: int, MaximumBatchingWindowInSeconds?: int, ...},
 *         RabbitMQBrokerParameters?: array{
 *             Credentials?: array,
 *             QueueName?: string,
 *             VirtualHost?: string,
 *             BatchSize?: int,
 *             MaximumBatchingWindowInSeconds?: int,
 *             ...,
 *         },
 *         ManagedStreamingKafkaParameters?: array{
 *             TopicName?: string,
 *             StartingPosition?: 'LATEST'|'TRIM_HORIZON',
 *             BatchSize?: int,
 *             MaximumBatchingWindowInSeconds?: int,
 *             ConsumerGroupID?: string,
 *             Credentials?: array,
 *             ...,
 *         },
 *         SelfManagedKafkaParameters?: array{
 *             TopicName?: string,
 *             StartingPosition?: 'LATEST'|'TRIM_HORIZON',
 *             AdditionalBootstrapServers?: list<string>,
 *             BatchSize?: int,
 *             MaximumBatchingWindowInSeconds?: int,
 *             ConsumerGroupID?: string,
 *             Credentials?: array,
 *             ServerRootCaCertificate?: string,
 *             Vpc?: array,
 *             ...,
 *         },
 *         ...,
 *     },
 *     Enrichment?: string,
 *     EnrichmentParameters?: array{
 *         InputTemplate?: string,
 *         HttpParameters?: array{
 *             PathParameterValues?: list<string>,
 *             HeaderParameters?: array<string, string>,
 *             QueryStringParameters?: array<string, string>,
 *             ...,
 *         },
 *         ...,
 *     },
 *     Target?: string,
 *     TargetParameters?: array{
 *         InputTemplate?: string,
 *         LambdaFunctionParameters?: array{InvocationType?: 'FIRE_AND_FORGET'|'REQUEST_RESPONSE', ...},
 *         StepFunctionStateMachineParameters?: array{InvocationType?: 'FIRE_AND_FORGET'|'REQUEST_RESPONSE', ...},
 *         KinesisStreamParameters?: array{PartitionKey?: string, ...},
 *         EcsTaskParameters?: array{
 *             TaskDefinitionArn?: string,
 *             TaskCount?: int,
 *             LaunchType?: 'EC2'|'EXTERNAL'|'FARGATE',
 *             NetworkConfiguration?: array,
 *             PlatformVersion?: string,
 *             Group?: string,
 *             CapacityProviderStrategy?: list<array>,
 *             EnableECSManagedTags?: bool,
 *             EnableExecuteCommand?: bool,
 *             PlacementConstraints?: list<array>,
 *             PlacementStrategy?: list<array>,
 *             PropagateTags?: 'TASK_DEFINITION',
 *             ReferenceId?: string,
 *             Overrides?: array,
 *             Tags?: list<array>,
 *             ...,
 *         },
 *         BatchJobParameters?: array{
 *             JobDefinition?: string,
 *             JobName?: string,
 *             ArrayProperties?: array,
 *             RetryStrategy?: array,
 *             ContainerOverrides?: array,
 *             DependsOn?: list<array>,
 *             Parameters?: array<string, string>,
 *             ...,
 *         },
 *         SqsQueueParameters?: array{MessageGroupId?: string, MessageDeduplicationId?: string, ...},
 *         HttpParameters?: array{
 *             PathParameterValues?: list<string>,
 *             HeaderParameters?: array<string, string>,
 *             QueryStringParameters?: array<string, string>,
 *             ...,
 *         },
 *         RedshiftDataParameters?: array{
 *             SecretManagerArn?: string,
 *             Database?: string,
 *             DbUser?: string,
 *             StatementName?: string,
 *             WithEvent?: bool,
 *             Sqls?: list<string>,
 *             ...,
 *         },
 *         SageMakerPipelineParameters?: array{PipelineParameterList?: list<array>, ...},
 *         EventBridgeEventBusParameters?: array{EndpointId?: string, DetailType?: string, Source?: string, Resources?: list<string>, Time?: string, ...},
 *         CloudWatchLogsParameters?: array{LogStreamName?: string, Timestamp?: string, ...},
 *         TimestreamParameters?: array{
 *             TimeValue?: string,
 *             EpochTimeUnit?: 'MICROSECONDS'|'MILLISECONDS'|'NANOSECONDS'|'SECONDS',
 *             TimeFieldType?: 'EPOCH'|'TIMESTAMP_FORMAT',
 *             TimestampFormat?: string,
 *             VersionValue?: string,
 *             DimensionMappings?: list<array>,
 *             SingleMeasureMappings?: list<array>,
 *             MultiMeasureMappings?: list<array>,
 *             ...,
 *         },
 *         ...,
 *     },
 *     RoleArn?: string,
 *     Tags?: array<string, string>,
 *     LogConfiguration?: array{
 *         S3LogDestination?: array{BucketName?: string, BucketOwner?: string, OutputFormat?: 'json'|'plain'|'w3c', Prefix?: string, ...},
 *         FirehoseLogDestination?: array{DeliveryStreamArn?: string, ...},
 *         CloudwatchLogsLogDestination?: array{LogGroupArn?: string, ...},
 *         Level?: 'ERROR'|'INFO'|'OFF'|'TRACE',
 *         IncludeExecutionData?: list<'ALL'>,
 *         ...,
 *     },
 *     KmsKeyIdentifier?: string,
 *     ...,
 * } $args = [])
 * @method \GuzzleHttp\Promise\Promise createPipeAsync(array $args = [])
 * @phpstan-method \GuzzleHttp\Promise\Promise createPipeAsync(array{
 *     Name?: string,
 *     Description?: string,
 *     DesiredState?: 'RUNNING'|'STOPPED',
 *     Source?: string,
 *     SourceParameters?: array{
 *         FilterCriteria?: array{Filters?: list<array>, ...},
 *         KinesisStreamParameters?: array{
 *             BatchSize?: int,
 *             DeadLetterConfig?: array,
 *             OnPartialBatchItemFailure?: 'AUTOMATIC_BISECT',
 *             MaximumBatchingWindowInSeconds?: int,
 *             MaximumRecordAgeInSeconds?: int,
 *             MaximumRetryAttempts?: int,
 *             ParallelizationFactor?: int,
 *             StartingPosition?: 'AT_TIMESTAMP'|'LATEST'|'TRIM_HORIZON',
 *             StartingPositionTimestamp?: int|string|\DateTimeInterface,
 *             ...,
 *         },
 *         DynamoDBStreamParameters?: array{
 *             BatchSize?: int,
 *             DeadLetterConfig?: array,
 *             OnPartialBatchItemFailure?: 'AUTOMATIC_BISECT',
 *             MaximumBatchingWindowInSeconds?: int,
 *             MaximumRecordAgeInSeconds?: int,
 *             MaximumRetryAttempts?: int,
 *             ParallelizationFactor?: int,
 *             StartingPosition?: 'LATEST'|'TRIM_HORIZON',
 *             ...,
 *         },
 *         SqsQueueParameters?: array{BatchSize?: int, MaximumBatchingWindowInSeconds?: int, ...},
 *         ActiveMQBrokerParameters?: array{Credentials?: array, QueueName?: string, BatchSize?: int, MaximumBatchingWindowInSeconds?: int, ...},
 *         RabbitMQBrokerParameters?: array{
 *             Credentials?: array,
 *             QueueName?: string,
 *             VirtualHost?: string,
 *             BatchSize?: int,
 *             MaximumBatchingWindowInSeconds?: int,
 *             ...,
 *         },
 *         ManagedStreamingKafkaParameters?: array{
 *             TopicName?: string,
 *             StartingPosition?: 'LATEST'|'TRIM_HORIZON',
 *             BatchSize?: int,
 *             MaximumBatchingWindowInSeconds?: int,
 *             ConsumerGroupID?: string,
 *             Credentials?: array,
 *             ...,
 *         },
 *         SelfManagedKafkaParameters?: array{
 *             TopicName?: string,
 *             StartingPosition?: 'LATEST'|'TRIM_HORIZON',
 *             AdditionalBootstrapServers?: list<string>,
 *             BatchSize?: int,
 *             MaximumBatchingWindowInSeconds?: int,
 *             ConsumerGroupID?: string,
 *             Credentials?: array,
 *             ServerRootCaCertificate?: string,
 *             Vpc?: array,
 *             ...,
 *         },
 *         ...,
 *     },
 *     Enrichment?: string,
 *     EnrichmentParameters?: array{
 *         InputTemplate?: string,
 *         HttpParameters?: array{
 *             PathParameterValues?: list<string>,
 *             HeaderParameters?: array<string, string>,
 *             QueryStringParameters?: array<string, string>,
 *             ...,
 *         },
 *         ...,
 *     },
 *     Target?: string,
 *     TargetParameters?: array{
 *         InputTemplate?: string,
 *         LambdaFunctionParameters?: array{InvocationType?: 'FIRE_AND_FORGET'|'REQUEST_RESPONSE', ...},
 *         StepFunctionStateMachineParameters?: array{InvocationType?: 'FIRE_AND_FORGET'|'REQUEST_RESPONSE', ...},
 *         KinesisStreamParameters?: array{PartitionKey?: string, ...},
 *         EcsTaskParameters?: array{
 *             TaskDefinitionArn?: string,
 *             TaskCount?: int,
 *             LaunchType?: 'EC2'|'EXTERNAL'|'FARGATE',
 *             NetworkConfiguration?: array,
 *             PlatformVersion?: string,
 *             Group?: string,
 *             CapacityProviderStrategy?: list<array>,
 *             EnableECSManagedTags?: bool,
 *             EnableExecuteCommand?: bool,
 *             PlacementConstraints?: list<array>,
 *             PlacementStrategy?: list<array>,
 *             PropagateTags?: 'TASK_DEFINITION',
 *             ReferenceId?: string,
 *             Overrides?: array,
 *             Tags?: list<array>,
 *             ...,
 *         },
 *         BatchJobParameters?: array{
 *             JobDefinition?: string,
 *             JobName?: string,
 *             ArrayProperties?: array,
 *             RetryStrategy?: array,
 *             ContainerOverrides?: array,
 *             DependsOn?: list<array>,
 *             Parameters?: array<string, string>,
 *             ...,
 *         },
 *         SqsQueueParameters?: array{MessageGroupId?: string, MessageDeduplicationId?: string, ...},
 *         HttpParameters?: array{
 *             PathParameterValues?: list<string>,
 *             HeaderParameters?: array<string, string>,
 *             QueryStringParameters?: array<string, string>,
 *             ...,
 *         },
 *         RedshiftDataParameters?: array{
 *             SecretManagerArn?: string,
 *             Database?: string,
 *             DbUser?: string,
 *             StatementName?: string,
 *             WithEvent?: bool,
 *             Sqls?: list<string>,
 *             ...,
 *         },
 *         SageMakerPipelineParameters?: array{PipelineParameterList?: list<array>, ...},
 *         EventBridgeEventBusParameters?: array{EndpointId?: string, DetailType?: string, Source?: string, Resources?: list<string>, Time?: string, ...},
 *         CloudWatchLogsParameters?: array{LogStreamName?: string, Timestamp?: string, ...},
 *         TimestreamParameters?: array{
 *             TimeValue?: string,
 *             EpochTimeUnit?: 'MICROSECONDS'|'MILLISECONDS'|'NANOSECONDS'|'SECONDS',
 *             TimeFieldType?: 'EPOCH'|'TIMESTAMP_FORMAT',
 *             TimestampFormat?: string,
 *             VersionValue?: string,
 *             DimensionMappings?: list<array>,
 *             SingleMeasureMappings?: list<array>,
 *             MultiMeasureMappings?: list<array>,
 *             ...,
 *         },
 *         ...,
 *     },
 *     RoleArn?: string,
 *     Tags?: array<string, string>,
 *     LogConfiguration?: array{
 *         S3LogDestination?: array{BucketName?: string, BucketOwner?: string, OutputFormat?: 'json'|'plain'|'w3c', Prefix?: string, ...},
 *         FirehoseLogDestination?: array{DeliveryStreamArn?: string, ...},
 *         CloudwatchLogsLogDestination?: array{LogGroupArn?: string, ...},
 *         Level?: 'ERROR'|'INFO'|'OFF'|'TRACE',
 *         IncludeExecutionData?: list<'ALL'>,
 *         ...,
 *     },
 *     KmsKeyIdentifier?: string,
 *     ...,
 * } $args = [])
 * @method \Aws\Result deletePipe(array $args = [])
 * @phpstan-method \Aws\Result deletePipe(array{Name?: string, ...} $args = [])
 * @method \GuzzleHttp\Promise\Promise deletePipeAsync(array $args = [])
 * @phpstan-method \GuzzleHttp\Promise\Promise deletePipeAsync(array{Name?: string, ...} $args = [])
 * @method \Aws\Result describePipe(array $args = [])
 * @phpstan-method \Aws\Result describePipe(array{Name?: string, ...} $args = [])
 * @method \GuzzleHttp\Promise\Promise describePipeAsync(array $args = [])
 * @phpstan-method \GuzzleHttp\Promise\Promise describePipeAsync(array{Name?: string, ...} $args = [])
 * @method \Aws\Result listPipes(array $args = [])
 * @phpstan-method \Aws\Result listPipes(array{
 *     NamePrefix?: string,
 *     DesiredState?: 'RUNNING'|'STOPPED',
 *     CurrentState?: 'CREATE_FAILED'|'CREATE_ROLLBACK_FAILED'|'CREATING'|'DELETE_FAILED'|'DELETE_ROLLBACK_FAILED'|'DELETING'|'RUNNING'|'STARTING'|'START_FAILED'|'STOPPED'|'STOPPING'|'STOP_FAILED'|'UPDATE_FAILED'|'UPDATE_ROLLBACK_FAILED'|'UPDATING',
 *     SourcePrefix?: string,
 *     TargetPrefix?: string,
 *     NextToken?: string,
 *     Limit?: int,
 *     ...,
 * } $args = [])
 * @method \GuzzleHttp\Promise\Promise listPipesAsync(array $args = [])
 * @phpstan-method \GuzzleHttp\Promise\Promise listPipesAsync(array{
 *     NamePrefix?: string,
 *     DesiredState?: 'RUNNING'|'STOPPED',
 *     CurrentState?: 'CREATE_FAILED'|'CREATE_ROLLBACK_FAILED'|'CREATING'|'DELETE_FAILED'|'DELETE_ROLLBACK_FAILED'|'DELETING'|'RUNNING'|'STARTING'|'START_FAILED'|'STOPPED'|'STOPPING'|'STOP_FAILED'|'UPDATE_FAILED'|'UPDATE_ROLLBACK_FAILED'|'UPDATING',
 *     SourcePrefix?: string,
 *     TargetPrefix?: string,
 *     NextToken?: string,
 *     Limit?: int,
 *     ...,
 * } $args = [])
 * @method \Aws\Result listTagsForResource(array $args = [])
 * @phpstan-method \Aws\Result listTagsForResource(array{resourceArn?: string, ...} $args = [])
 * @method \GuzzleHttp\Promise\Promise listTagsForResourceAsync(array $args = [])
 * @phpstan-method \GuzzleHttp\Promise\Promise listTagsForResourceAsync(array{resourceArn?: string, ...} $args = [])
 * @method \Aws\Result startPipe(array $args = [])
 * @phpstan-method \Aws\Result startPipe(array{Name?: string, ...} $args = [])
 * @method \GuzzleHttp\Promise\Promise startPipeAsync(array $args = [])
 * @phpstan-method \GuzzleHttp\Promise\Promise startPipeAsync(array{Name?: string, ...} $args = [])
 * @method \Aws\Result stopPipe(array $args = [])
 * @phpstan-method \Aws\Result stopPipe(array{Name?: string, ...} $args = [])
 * @method \GuzzleHttp\Promise\Promise stopPipeAsync(array $args = [])
 * @phpstan-method \GuzzleHttp\Promise\Promise stopPipeAsync(array{Name?: string, ...} $args = [])
 * @method \Aws\Result tagResource(array $args = [])
 * @phpstan-method \Aws\Result tagResource(array{resourceArn?: string, tags?: array<string, string>, ...} $args = [])
 * @method \GuzzleHttp\Promise\Promise tagResourceAsync(array $args = [])
 * @phpstan-method \GuzzleHttp\Promise\Promise tagResourceAsync(array{resourceArn?: string, tags?: array<string, string>, ...} $args = [])
 * @method \Aws\Result untagResource(array $args = [])
 * @phpstan-method \Aws\Result untagResource(array{resourceArn?: string, tagKeys?: list<string>, ...} $args = [])
 * @method \GuzzleHttp\Promise\Promise untagResourceAsync(array $args = [])
 * @phpstan-method \GuzzleHttp\Promise\Promise untagResourceAsync(array{resourceArn?: string, tagKeys?: list<string>, ...} $args = [])
 * @method \Aws\Result updatePipe(array $args = [])
 * @phpstan-method \Aws\Result updatePipe(array{
 *     Name?: string,
 *     Description?: string,
 *     DesiredState?: 'RUNNING'|'STOPPED',
 *     SourceParameters?: array{
 *         FilterCriteria?: array{Filters?: list<array>, ...},
 *         KinesisStreamParameters?: array{
 *             BatchSize?: int,
 *             DeadLetterConfig?: array,
 *             OnPartialBatchItemFailure?: 'AUTOMATIC_BISECT',
 *             MaximumBatchingWindowInSeconds?: int,
 *             MaximumRecordAgeInSeconds?: int,
 *             MaximumRetryAttempts?: int,
 *             ParallelizationFactor?: int,
 *             ...,
 *         },
 *         DynamoDBStreamParameters?: array{
 *             BatchSize?: int,
 *             DeadLetterConfig?: array,
 *             OnPartialBatchItemFailure?: 'AUTOMATIC_BISECT',
 *             MaximumBatchingWindowInSeconds?: int,
 *             MaximumRecordAgeInSeconds?: int,
 *             MaximumRetryAttempts?: int,
 *             ParallelizationFactor?: int,
 *             ...,
 *         },
 *         SqsQueueParameters?: array{BatchSize?: int, MaximumBatchingWindowInSeconds?: int, ...},
 *         ActiveMQBrokerParameters?: array{Credentials?: array, BatchSize?: int, MaximumBatchingWindowInSeconds?: int, ...},
 *         RabbitMQBrokerParameters?: array{Credentials?: array, BatchSize?: int, MaximumBatchingWindowInSeconds?: int, ...},
 *         ManagedStreamingKafkaParameters?: array{BatchSize?: int, Credentials?: array, MaximumBatchingWindowInSeconds?: int, ...},
 *         SelfManagedKafkaParameters?: array{
 *             BatchSize?: int,
 *             MaximumBatchingWindowInSeconds?: int,
 *             Credentials?: array,
 *             ServerRootCaCertificate?: string,
 *             Vpc?: array,
 *             ...,
 *         },
 *         ...,
 *     },
 *     Enrichment?: string,
 *     EnrichmentParameters?: array{
 *         InputTemplate?: string,
 *         HttpParameters?: array{
 *             PathParameterValues?: list<string>,
 *             HeaderParameters?: array<string, string>,
 *             QueryStringParameters?: array<string, string>,
 *             ...,
 *         },
 *         ...,
 *     },
 *     Target?: string,
 *     TargetParameters?: array{
 *         InputTemplate?: string,
 *         LambdaFunctionParameters?: array{InvocationType?: 'FIRE_AND_FORGET'|'REQUEST_RESPONSE', ...},
 *         StepFunctionStateMachineParameters?: array{InvocationType?: 'FIRE_AND_FORGET'|'REQUEST_RESPONSE', ...},
 *         KinesisStreamParameters?: array{PartitionKey?: string, ...},
 *         EcsTaskParameters?: array{
 *             TaskDefinitionArn?: string,
 *             TaskCount?: int,
 *             LaunchType?: 'EC2'|'EXTERNAL'|'FARGATE',
 *             NetworkConfiguration?: array,
 *             PlatformVersion?: string,
 *             Group?: string,
 *             CapacityProviderStrategy?: list<array>,
 *             EnableECSManagedTags?: bool,
 *             EnableExecuteCommand?: bool,
 *             PlacementConstraints?: list<array>,
 *             PlacementStrategy?: list<array>,
 *             PropagateTags?: 'TASK_DEFINITION',
 *             ReferenceId?: string,
 *             Overrides?: array,
 *             Tags?: list<array>,
 *             ...,
 *         },
 *         BatchJobParameters?: array{
 *             JobDefinition?: string,
 *             JobName?: string,
 *             ArrayProperties?: array,
 *             RetryStrategy?: array,
 *             ContainerOverrides?: array,
 *             DependsOn?: list<array>,
 *             Parameters?: array<string, string>,
 *             ...,
 *         },
 *         SqsQueueParameters?: array{MessageGroupId?: string, MessageDeduplicationId?: string, ...},
 *         HttpParameters?: array{
 *             PathParameterValues?: list<string>,
 *             HeaderParameters?: array<string, string>,
 *             QueryStringParameters?: array<string, string>,
 *             ...,
 *         },
 *         RedshiftDataParameters?: array{
 *             SecretManagerArn?: string,
 *             Database?: string,
 *             DbUser?: string,
 *             StatementName?: string,
 *             WithEvent?: bool,
 *             Sqls?: list<string>,
 *             ...,
 *         },
 *         SageMakerPipelineParameters?: array{PipelineParameterList?: list<array>, ...},
 *         EventBridgeEventBusParameters?: array{EndpointId?: string, DetailType?: string, Source?: string, Resources?: list<string>, Time?: string, ...},
 *         CloudWatchLogsParameters?: array{LogStreamName?: string, Timestamp?: string, ...},
 *         TimestreamParameters?: array{
 *             TimeValue?: string,
 *             EpochTimeUnit?: 'MICROSECONDS'|'MILLISECONDS'|'NANOSECONDS'|'SECONDS',
 *             TimeFieldType?: 'EPOCH'|'TIMESTAMP_FORMAT',
 *             TimestampFormat?: string,
 *             VersionValue?: string,
 *             DimensionMappings?: list<array>,
 *             SingleMeasureMappings?: list<array>,
 *             MultiMeasureMappings?: list<array>,
 *             ...,
 *         },
 *         ...,
 *     },
 *     RoleArn?: string,
 *     LogConfiguration?: array{
 *         S3LogDestination?: array{BucketName?: string, BucketOwner?: string, OutputFormat?: 'json'|'plain'|'w3c', Prefix?: string, ...},
 *         FirehoseLogDestination?: array{DeliveryStreamArn?: string, ...},
 *         CloudwatchLogsLogDestination?: array{LogGroupArn?: string, ...},
 *         Level?: 'ERROR'|'INFO'|'OFF'|'TRACE',
 *         IncludeExecutionData?: list<'ALL'>,
 *         ...,
 *     },
 *     KmsKeyIdentifier?: string,
 *     ...,
 * } $args = [])
 * @method \GuzzleHttp\Promise\Promise updatePipeAsync(array $args = [])
 * @phpstan-method \GuzzleHttp\Promise\Promise updatePipeAsync(array{
 *     Name?: string,
 *     Description?: string,
 *     DesiredState?: 'RUNNING'|'STOPPED',
 *     SourceParameters?: array{
 *         FilterCriteria?: array{Filters?: list<array>, ...},
 *         KinesisStreamParameters?: array{
 *             BatchSize?: int,
 *             DeadLetterConfig?: array,
 *             OnPartialBatchItemFailure?: 'AUTOMATIC_BISECT',
 *             MaximumBatchingWindowInSeconds?: int,
 *             MaximumRecordAgeInSeconds?: int,
 *             MaximumRetryAttempts?: int,
 *             ParallelizationFactor?: int,
 *             ...,
 *         },
 *         DynamoDBStreamParameters?: array{
 *             BatchSize?: int,
 *             DeadLetterConfig?: array,
 *             OnPartialBatchItemFailure?: 'AUTOMATIC_BISECT',
 *             MaximumBatchingWindowInSeconds?: int,
 *             MaximumRecordAgeInSeconds?: int,
 *             MaximumRetryAttempts?: int,
 *             ParallelizationFactor?: int,
 *             ...,
 *         },
 *         SqsQueueParameters?: array{BatchSize?: int, MaximumBatchingWindowInSeconds?: int, ...},
 *         ActiveMQBrokerParameters?: array{Credentials?: array, BatchSize?: int, MaximumBatchingWindowInSeconds?: int, ...},
 *         RabbitMQBrokerParameters?: array{Credentials?: array, BatchSize?: int, MaximumBatchingWindowInSeconds?: int, ...},
 *         ManagedStreamingKafkaParameters?: array{BatchSize?: int, Credentials?: array, MaximumBatchingWindowInSeconds?: int, ...},
 *         SelfManagedKafkaParameters?: array{
 *             BatchSize?: int,
 *             MaximumBatchingWindowInSeconds?: int,
 *             Credentials?: array,
 *             ServerRootCaCertificate?: string,
 *             Vpc?: array,
 *             ...,
 *         },
 *         ...,
 *     },
 *     Enrichment?: string,
 *     EnrichmentParameters?: array{
 *         InputTemplate?: string,
 *         HttpParameters?: array{
 *             PathParameterValues?: list<string>,
 *             HeaderParameters?: array<string, string>,
 *             QueryStringParameters?: array<string, string>,
 *             ...,
 *         },
 *         ...,
 *     },
 *     Target?: string,
 *     TargetParameters?: array{
 *         InputTemplate?: string,
 *         LambdaFunctionParameters?: array{InvocationType?: 'FIRE_AND_FORGET'|'REQUEST_RESPONSE', ...},
 *         StepFunctionStateMachineParameters?: array{InvocationType?: 'FIRE_AND_FORGET'|'REQUEST_RESPONSE', ...},
 *         KinesisStreamParameters?: array{PartitionKey?: string, ...},
 *         EcsTaskParameters?: array{
 *             TaskDefinitionArn?: string,
 *             TaskCount?: int,
 *             LaunchType?: 'EC2'|'EXTERNAL'|'FARGATE',
 *             NetworkConfiguration?: array,
 *             PlatformVersion?: string,
 *             Group?: string,
 *             CapacityProviderStrategy?: list<array>,
 *             EnableECSManagedTags?: bool,
 *             EnableExecuteCommand?: bool,
 *             PlacementConstraints?: list<array>,
 *             PlacementStrategy?: list<array>,
 *             PropagateTags?: 'TASK_DEFINITION',
 *             ReferenceId?: string,
 *             Overrides?: array,
 *             Tags?: list<array>,
 *             ...,
 *         },
 *         BatchJobParameters?: array{
 *             JobDefinition?: string,
 *             JobName?: string,
 *             ArrayProperties?: array,
 *             RetryStrategy?: array,
 *             ContainerOverrides?: array,
 *             DependsOn?: list<array>,
 *             Parameters?: array<string, string>,
 *             ...,
 *         },
 *         SqsQueueParameters?: array{MessageGroupId?: string, MessageDeduplicationId?: string, ...},
 *         HttpParameters?: array{
 *             PathParameterValues?: list<string>,
 *             HeaderParameters?: array<string, string>,
 *             QueryStringParameters?: array<string, string>,
 *             ...,
 *         },
 *         RedshiftDataParameters?: array{
 *             SecretManagerArn?: string,
 *             Database?: string,
 *             DbUser?: string,
 *             StatementName?: string,
 *             WithEvent?: bool,
 *             Sqls?: list<string>,
 *             ...,
 *         },
 *         SageMakerPipelineParameters?: array{PipelineParameterList?: list<array>, ...},
 *         EventBridgeEventBusParameters?: array{EndpointId?: string, DetailType?: string, Source?: string, Resources?: list<string>, Time?: string, ...},
 *         CloudWatchLogsParameters?: array{LogStreamName?: string, Timestamp?: string, ...},
 *         TimestreamParameters?: array{
 *             TimeValue?: string,
 *             EpochTimeUnit?: 'MICROSECONDS'|'MILLISECONDS'|'NANOSECONDS'|'SECONDS',
 *             TimeFieldType?: 'EPOCH'|'TIMESTAMP_FORMAT',
 *             TimestampFormat?: string,
 *             VersionValue?: string,
 *             DimensionMappings?: list<array>,
 *             SingleMeasureMappings?: list<array>,
 *             MultiMeasureMappings?: list<array>,
 *             ...,
 *         },
 *         ...,
 *     },
 *     RoleArn?: string,
 *     LogConfiguration?: array{
 *         S3LogDestination?: array{BucketName?: string, BucketOwner?: string, OutputFormat?: 'json'|'plain'|'w3c', Prefix?: string, ...},
 *         FirehoseLogDestination?: array{DeliveryStreamArn?: string, ...},
 *         CloudwatchLogsLogDestination?: array{LogGroupArn?: string, ...},
 *         Level?: 'ERROR'|'INFO'|'OFF'|'TRACE',
 *         IncludeExecutionData?: list<'ALL'>,
 *         ...,
 *     },
 *     KmsKeyIdentifier?: string,
 *     ...,
 * } $args = [])
 */
class PipesClient extends AwsClient {}
