<?php return [
  'operations' => [
    'AddEventSource' => '<p>Identifies an Amazon Kinesis stream as the event source for an AWS Lambda function. AWS Lambda invokes the specified function when records are posted to the stream.</p> <p>This is the pull model, where AWS Lambda invokes the function. For more information, go to <a href="http://docs.aws.amazon.com/lambda/latest/dg/lambda-introduction.html">AWS LambdaL How it Works</a> in the AWS Lambda Developer Guide.</p> <p>This association between an Amazon Kinesis stream and an AWS Lambda function is called the event source mapping. You provide the configuration information (for example, which stream to read from and which AWS Lambda function to invoke] for the event source mapping in the request body.</p> <p>This operation requires permission for the <code>iam:PassRole</code> action for the IAM role. It also requires permission for the <code>lambda:AddEventSource</code> action.</p>',
    'DeleteFunction' => '<p>Deletes the specified Lambda function code and configuration.</p> <p>This operation requires permission for the <code>lambda:DeleteFunction</code> action.</p>',
    'GetEventSource' => '<p>Returns configuration information for the specified event source mapping (see <a>AddEventSource</a>].</p> <p>This operation requires permission for the <code>lambda:GetEventSource</code> action.</p>',
    'GetFunction' => '<p>Returns the configuration information of the Lambda function and a presigned URL link to the .zip file you uploaded with <a>UploadFunction</a> so you can download the .zip file. Note that the URL is valid for up to 10 minutes. The configuration information is the same information you provided as parameters when uploading the function.</p> <p>This operation requires permission for the <code>lambda:GetFunction</code> action.</p>',
    'GetFunctionConfiguration' => '<p>Returns the configuration information of the Lambda function. This the same information you provided as parameters when uploading the function by using <a>UploadFunction</a>.</p> <p>This operation requires permission for the <code>lambda:GetFunctionConfiguration</code> operation.</p>',
    'InvokeAsync' => '<p>Submits an invocation request to AWS Lambda. Upon receiving the request, Lambda executes the specified function asynchronously. To see the logs generated by the Lambda function execution, see the CloudWatch logs console.</p> <p>This operation requires permission for the <code>lambda:InvokeAsync</code> action.</p>',
    'ListEventSources' => '<p>Returns a list of event source mappings. For each mapping, the API returns configuration information (see <a>AddEventSource</a>]. You can optionally specify filters to retrieve specific event source mappings.</p> <p>This operation requires permission for the <code>lambda:ListEventSources</code> action.</p>',
    'ListFunctions' => '<p>Returns a list of your Lambda functions. For each function, the response includes the function configuration information. You must use <a>GetFunction</a> to retrieve the code for your function.</p> <p>This operation requires permission for the <code>lambda:ListFunctions</code> action.</p>',
    'RemoveEventSource' => '<p>Removes an event source mapping. This means AWS Lambda will no longer invoke the function for events in the associated source.</p> <p>This operation requires permission for the <code>lambda:RemoveEventSource</code> action.</p>',
    'UpdateFunctionConfiguration' => '<p>Updates the configuration parameters for the specified Lambda function by using the values provided in the request. You provide only the parameters you want to change. This operation must only be used on an existing Lambda function and cannot be used to update the function\'s code. </p> <p>This operation requires permission for the <code>lambda:UpdateFunctionConfiguration</code> action.</p>',
    'UploadFunction' => '<p>Creates a new Lambda function or updates an existing function. The function metadata is created from the request parameters, and the code for the function is provided by a .zip file in the request body. If the function name already exists, the existing Lambda function is updated with the new code and metadata. </p> <p>This operation requires permission for the <code>lambda:UploadFunction</code> action.</p>',
  ],
  'service' => '<fullname>AWS Lambda</fullname> <p><b>Overview</b></p> <p>This is the AWS Lambda API Reference. The AWS Lambda Developer Guide provides additional information. For the service overview, go to <a href="http://docs.aws.amazon.com/lambda/latest/dg/welcome.html">What is AWS Lambda</a>, and for information about how the service works, go to <a href="http://docs.aws.amazon.com/lambda/latest/dg/lambda-introduction.html">AWS LambdaL How it Works</a> in the AWS Lambda Developer Guide.</p>',
  'shapes' => [
    'AddEventSourceRequest' => [
      'base' => NULL,
      'refs' => [],
    ],
    'Blob' => [
      'base' => NULL,
      'refs' => [
        'InvokeAsyncRequest$InvokeArgs' => '<p>JSON that you want to provide to your Lambda function as input.</p>',
        'UploadFunctionRequest$FunctionZip' => '<p>A .zip file containing your packaged source code. For more information about creating a .zip file, go to <a href="http://docs.aws.amazon.com/lambda/latest/dg/walkthrough-custom-events.html">AWS LambdaL How it Works</a> in the AWS Lambda Developer Guide. </p>',
      ],
    ],
    'DeleteFunctionRequest' => [
      'base' => NULL,
      'refs' => [],
    ],
    'Description' => [
      'base' => NULL,
      'refs' => [
        'FunctionConfiguration$Description' => '<p>The user-provided description.</p>',
        'UpdateFunctionConfigurationRequest$Description' => '<p>A short user-defined function description. Lambda does not use this value. Assign a meaningful description as you see fit.</p>',
        'UploadFunctionRequest$Description' => '<p>A short, user-defined function description. Lambda does not use this value. Assign a meaningful description as you see fit.</p>',
      ],
    ],
    'EventSourceConfiguration' => [
      'base' => '<p>Describes mapping between an Amazon Kinesis stream and a Lambda function.</p>',
      'refs' => [
        'EventSourceList$member' => NULL,
      ],
    ],
    'EventSourceList' => [
      'base' => NULL,
      'refs' => [
        'ListEventSourcesResponse$EventSources' => '<p>An arrary of <code>EventSourceConfiguration</code> objects.</p>',
      ],
    ],
    'FunctionArn' => [
      'base' => NULL,
      'refs' => [
        'FunctionConfiguration$FunctionARN' => '<p>The Amazon Resource Name (ARN] assigned to the function.</p>',
      ],
    ],
    'FunctionCodeLocation' => [
      'base' => '<p>The object for the Lambda function location.</p>',
      'refs' => [
        'GetFunctionResponse$Code' => NULL,
      ],
    ],
    'FunctionConfiguration' => [
      'base' => '<p>A complex type that describes function metadata.</p>',
      'refs' => [
        'FunctionList$member' => NULL,
        'GetFunctionResponse$Configuration' => NULL,
      ],
    ],
    'FunctionList' => [
      'base' => NULL,
      'refs' => [
        'ListFunctionsResponse$Functions' => '<p>A list of Lambda functions.</p>',
      ],
    ],
    'FunctionName' => [
      'base' => NULL,
      'refs' => [
        'AddEventSourceRequest$FunctionName' => '<p>The Lambda function to invoke when AWS Lambda detects an event on the stream.</p>',
        'DeleteFunctionRequest$FunctionName' => '<p>The Lambda function to delete.</p>',
        'EventSourceConfiguration$FunctionName' => '<p>The Lambda function to invoke when AWS Lambda detects an event on the stream.</p>',
        'FunctionConfiguration$FunctionName' => '<p>The name of the function.</p>',
        'GetFunctionConfigurationRequest$FunctionName' => '<p>The name of the Lambda function for which you want to retrieve the configuration information.</p>',
        'GetFunctionRequest$FunctionName' => '<p>The Lambda function name.</p>',
        'InvokeAsyncRequest$FunctionName' => '<p>The Lambda function name.</p>',
        'ListEventSourcesRequest$FunctionName' => '<p>The name of the AWS Lambda function.</p>',
        'UpdateFunctionConfigurationRequest$FunctionName' => '<p>The name of the Lambda function.</p>',
        'UploadFunctionRequest$FunctionName' => '<p>The name you want to assign to the function you are uploading. The function names appear in the console and are returned in the <a>ListFunctions</a> API. Function names are used to specify functions to other AWS Lambda APIs, such as <a>InvokeAsync</a>. </p>',
      ],
    ],
    'GetEventSourceRequest' => [
      'base' => NULL,
      'refs' => [],
    ],
    'GetFunctionConfigurationRequest' => [
      'base' => NULL,
      'refs' => [],
    ],
    'GetFunctionRequest' => [
      'base' => NULL,
      'refs' => [],
    ],
    'GetFunctionResponse' => [
      'base' => '<p>This response contains the object for AWS Lambda function location (see <a>API_FunctionCodeLocation</a></p>',
      'refs' => [],
    ],
    'Handler' => [
      'base' => NULL,
      'refs' => [
        'FunctionConfiguration$Handler' => '<p>The function Lambda calls to begin executing your function.</p>',
        'UpdateFunctionConfigurationRequest$Handler' => '<p>The function that Lambda calls to begin executing your function. For Node.js, it is the <i>module-name.export</i> value in your function. </p>',
        'UploadFunctionRequest$Handler' => '<p>The function that Lambda calls to begin execution. For Node.js, it is the <i>module-name</i>.<i>export</i> value in your function. </p>',
      ],
    ],
    'HttpStatus' => [
      'base' => NULL,
      'refs' => [
        'InvokeAsyncResponse$Status' => '<p>It will be 202 upon success.</p>',
      ],
    ],
    'Integer' => [
      'base' => NULL,
      'refs' => [
        'AddEventSourceRequest$BatchSize' => '<p>The largest number of records that AWS Lambda will give to your function in a single event. The default is 100 records.</p>',
        'EventSourceConfiguration$BatchSize' => '<p>The largest number of records that AWS Lambda will POST in the invocation request to your function.</p>',
      ],
    ],
    'InvalidParameterValueException' => [
      'base' => '<p>One of the parameters in the request is invalid. For example, if you provided an IAM role for AWS Lambda to assume in the <code>UploadFunction</code> or the <code>UpdateFunctionConfiguration</code> API, that AWS Lambda is unable to assume you will get this exception. </p>',
      'refs' => [],
    ],
    'InvalidRequestContentException' => [
      'base' => '<p>The request body could not be parsed as JSON.</p>',
      'refs' => [],
    ],
    'InvokeAsyncRequest' => [
      'base' => NULL,
      'refs' => [],
    ],
    'InvokeAsyncResponse' => [
      'base' => '<p>Upon success, it returns empty response. Otherwise, throws an exception.</p>',
      'refs' => [],
    ],
    'ListEventSourcesRequest' => [
      'base' => NULL,
      'refs' => [],
    ],
    'ListEventSourcesResponse' => [
      'base' => '<p>Contains a list of event sources (see <a>API_EventSourceConfiguration</a>]</p>',
      'refs' => [],
    ],
    'ListFunctionsRequest' => [
      'base' => NULL,
      'refs' => [],
    ],
    'ListFunctionsResponse' => [
      'base' => '<p>Contains a list of AWS Lambda function configurations (see <a>API_FunctionConfiguration</a>.</p>',
      'refs' => [],
    ],
    'Long' => [
      'base' => NULL,
      'refs' => [
        'FunctionConfiguration$CodeSize' => '<p>The size, in bytes, of the function .zip file you uploaded.</p>',
      ],
    ],
    'Map' => [
      'base' => NULL,
      'refs' => [
        'AddEventSourceRequest$Parameters' => '<p>A map (key-value pairs] defining the configuration for AWS Lambda to use when reading the event source. Currently, AWS Lambda supports only the <code>InitialPositionInStream</code> key. The valid values are: "TRIM_HORIZON" and "LATEST". The default value is "TRIM_HORIZON". For more information, go to <a href="http://docs.aws.amazon.com/kinesis/latest/APIReference/API_GetShardIterator.html#Kinesis-GetShardIterator-request-ShardIteratorType">ShardIteratorType</a> in the Amazon Kinesis Service API Reference. </p>',
        'EventSourceConfiguration$Parameters' => '<p>The map (key-value pairs] defining the configuration for AWS Lambda to use when reading the event source.</p>',
      ],
    ],
    'MaxListItems' => [
      'base' => NULL,
      'refs' => [
        'ListEventSourcesRequest$MaxItems' => '<p>Optional integer. Specifies the maximum number of event sources to return in response. This value must be greater than 0.</p>',
        'ListFunctionsRequest$MaxItems' => '<p>Optional integer. Specifies the maximum number of AWS Lambda functions to return in response. This parameter value must be greater than 0.</p>',
      ],
    ],
    'MemorySize' => [
      'base' => NULL,
      'refs' => [
        'FunctionConfiguration$MemorySize' => '<p>The memory size, in MB, you configured for the function. Must be a multiple of 64 MB.</p>',
        'UpdateFunctionConfigurationRequest$MemorySize' => '<p>The amount of memory, in MB, your Lambda function is given. Lambda uses this memory size to infer the amount of CPU allocated to your function. Your function use-case determines your CPU and memory requirements. For example, a database operation might need less memory compared to an image processing function. The default value is 128 MB. The value must be a multiple of 64 MB.</p>',
        'UploadFunctionRequest$MemorySize' => '<p>The amount of memory, in MB, your Lambda function is given. Lambda uses this memory size to infer the amount of CPU allocated to your function. Your function use-case determines your CPU and memory requirements. For example, database operation might need less memory compared to image processing function. The default value is 128 MB. The value must be a multiple of 64 MB.</p>',
      ],
    ],
    'Mode' => [
      'base' => NULL,
      'refs' => [
        'FunctionConfiguration$Mode' => '<p>The type of the Lambda function you uploaded. </p>',
        'UploadFunctionRequest$Mode' => '<p>How the Lambda function will be invoked. Lambda supports only the "event" mode. </p>',
      ],
    ],
    'RemoveEventSourceRequest' => [
      'base' => NULL,
      'refs' => [],
    ],
    'ResourceNotFoundException' => [
      'base' => '<p>The function or the event source specified in the request does not exist.</p>',
      'refs' => [],
    ],
    'RoleArn' => [
      'base' => NULL,
      'refs' => [
        'AddEventSourceRequest$Role' => '<p>The ARN of the IAM role (invocation role] that AWS Lambda can assume to read from the stream and invoke the function.</p>',
        'EventSourceConfiguration$Role' => '<p>The ARN of the IAM role (invocation role] that AWS Lambda can assume to read from the stream and invoke the function.</p>',
        'FunctionConfiguration$Role' => '<p>The Amazon Resource Name (ARN] of the IAM role that Lambda assumes when it executes your function to access any other Amazon Web Services (AWS] resources.</p>',
        'UpdateFunctionConfigurationRequest$Role' => '<p>The Amazon Resource Name (ARN] of the IAM role that Lambda will assume when it executes your function. </p>',
        'UploadFunctionRequest$Role' => '<p>The Amazon Resource Name (ARN] of the IAM role that Lambda assumes when it executes your function to access any other Amazon Web Services (AWS] resources. </p>',
      ],
    ],
    'Runtime' => [
      'base' => NULL,
      'refs' => [
        'FunctionConfiguration$Runtime' => '<p>The runtime environment for the Lambda function.</p>',
        'UploadFunctionRequest$Runtime' => '<p>The runtime environment for the Lambda function you are uploading. Currently, Lambda supports only "nodejs" as the runtime.</p>',
      ],
    ],
    'ServiceException' => [
      'base' => '<p>The AWS Lambda service encountered an internal error.</p>',
      'refs' => [],
    ],
    'String' => [
      'base' => NULL,
      'refs' => [
        'AddEventSourceRequest$EventSource' => '<p>The Amazon Resource Name (ARN] of the Amazon Kinesis stream that is the event source. Any record added to this stream causes AWS Lambda to invoke your Lambda function. AWS Lambda POSTs the Amazon Kinesis event, containing records, to your Lambda function as JSON.</p>',
        'EventSourceConfiguration$UUID' => '<p>The AWS Lambda assigned opaque identifier for the mapping.</p>',
        'EventSourceConfiguration$EventSource' => '<p>The Amazon Resource Name (ARN] of the Amazon Kinesis stream that is the source of events.</p>',
        'EventSourceConfiguration$Status' => '<p>The description of the health of the event source mapping. Valid values are: "PENDING", "OK", and "PROBLEM:<i>message</i>". Initially this staus is "PENDING". When AWS Lambda begins processing events, it changes the status to "OK".</p>',
        'FunctionCodeLocation$RepositoryType' => '<p>The repository from which you can download the function.</p>',
        'FunctionCodeLocation$Location' => '<p>The presigned URL you can use to download the function\'s .zip file that you previously uploaded. The URL is valid for up to 10 minutes.</p>',
        'FunctionConfiguration$ConfigurationId' => '<p>A Lambda-assigned unique identifier for the current function code and related configuration.</p>',
        'GetEventSourceRequest$UUID' => '<p>The AWS Lambda assigned ID of the event source mapping.</p>',
        'InvalidParameterValueException$Type' => NULL,
        'InvalidParameterValueException$message' => NULL,
        'InvalidRequestContentException$Type' => NULL,
        'InvalidRequestContentException$message' => NULL,
        'ListEventSourcesRequest$EventSourceArn' => '<p>The Amazon Resource Name (ARN] of the Amazon Kinesis stream.</p>',
        'ListEventSourcesRequest$Marker' => '<p>Optional string. An opaque pagination token returned from a previous <code>ListEventSources</code> operation. If present, specifies to continue the list from where the returning call left off. </p>',
        'ListEventSourcesResponse$NextMarker' => '<p>A string, present if there are more event source mappings.</p>',
        'ListFunctionsRequest$Marker' => '<p>Optional string. An opaque pagination token returned from a previous <code>ListFunctions</code> operation. If present, indicates where to continue the listing. </p>',
        'ListFunctionsResponse$NextMarker' => '<p>A string, present if there are more functions.</p>',
        'Map$key' => NULL,
        'Map$value' => NULL,
        'RemoveEventSourceRequest$UUID' => '<p>The event source mapping ID.</p>',
        'ResourceNotFoundException$Type' => NULL,
        'ResourceNotFoundException$Message' => NULL,
        'ServiceException$Type' => NULL,
        'ServiceException$Message' => NULL,
      ],
    ],
    'Timeout' => [
      'base' => NULL,
      'refs' => [
        'FunctionConfiguration$Timeout' => '<p>The function execution time at which Lambda should terminate the function. Because the execution time has cost implications, we recommend you set this value based on your expected execution time. The default is 3 seconds. </p>',
        'UpdateFunctionConfigurationRequest$Timeout' => '<p>The function execution time at which Lambda should terminate the function. Because the execution time has cost implications, we recommend you set this value based on your expected execution time. The default is 3 seconds. </p>',
        'UploadFunctionRequest$Timeout' => '<p>The function execution time at which Lambda should terminate the function. Because the execution time has cost implications, we recommend you set this value based on your expected execution time. The default is 3 seconds. </p>',
      ],
    ],
    'Timestamp' => [
      'base' => NULL,
      'refs' => [
        'EventSourceConfiguration$LastModified' => '<p>The UTC time string indicating the last time the event mapping was updated.</p>',
        'FunctionConfiguration$LastModified' => '<p>The timestamp of the last time you updated the function.</p>',
      ],
    ],
    'UpdateFunctionConfigurationRequest' => [
      'base' => NULL,
      'refs' => [],
    ],
    'UploadFunctionRequest' => [
      'base' => NULL,
      'refs' => [],
    ],
    'Boolean' => [
      'base' => NULL,
      'refs' => [
        'EventSourceConfiguration$IsActive' => '<p>Indicates whether the event source mapping is currently honored. Events are only processes if IsActive is true.</p>',
      ],
    ],
  ],
];
